### ISSUE TITLE
Need better instrustions

### ISSUE THREAD

**Issue by jesspesale** [learn-co-curriculum/rails-activerecord-model-rails-lab#12]
I spent a solid 30 minutes trying to figure out why my migration wasnt working. Even hopped on a zoom call with an instructor for another 20 minutes and went through basically all the same steps I went through by myself and then finally realized it wasn't working because my migration file was not inside a "migrate" folder. 

In this lab and the previous one they should definitely state that your migrations need to be in that folder. I do not remember ever learning that and it took up quite a bit of time to try to figure out.

**Comment by bal360** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
