### ISSUE TITLE
ActiveRecord Model and Rails Lab missing crucial detail in Instructions

### ISSUE THREAD

**Issue by doosemavis** [learn-co-curriculum/rails-activerecord-model-rails-lab#13]
Hi there!  Was helping a student with the `ActiveRecord Models and Rails Lab` and while attempting to run `rake db:migrate` as you do, there was no error or information being outputted in the terminal to help assist this error.  The solution was the create a `migrate` directory inside the `db` directory where your `create_table` file would live.  The Instructions are missing this crucial detail and quite a few students are having this problem as well.  

What is the proper channel in resolving this issue for the curriculum? 
Or does anyone think this would be a good idea to add that into the instructions as a note or something to assist students in avoiding the confusion? 

Here is the instructions snippet from the lab for reference: 
![Screen Shot 2021-04-05 at 6 58 32 PM](https://user-images.githubusercontent.com/70960898/113640695-a928dc00-9641-11eb-8dfb-883166c5ddab.png)

Hope this is helpful!

**Comment by doosemavis** [comment]
@lizbur10  TADA! 😸

**Comment by lizbur10** [comment]
@bal360

**Comment by bal360** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
