### ISSUE TITLE
After removing the Gemfile.lock from this repo, I still can't `bundle install` on Mac M1.

### ISSUE THREAD

**Issue by drewkeat** [learn-co-curriculum/rails-activerecord-model-rails-lab#19]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.

## Describe the bug

Write a clear and concise description of what the bug is. Include the file and
line number(s) if possible.

## What is the expected behavior?

Write a clear and concise description of what you expected to happen.

## Screenshots

If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X
- [ ] WSL
- [ ] Linux

**Comment by ihollander** [comment]
Hi @drewkeat , thanks for raising this issue. In order to try and resolve it, we need a bit more information. Can you provide some more details about what the problem is exactly? Are you seeing any error messages output when running `bundle install`?
