### ISSUE TITLE
URL update needed

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rails-activerecord-model-rails-lab#2]
<img width="433" alt="screen shot 2016-01-01 at 5 02 05 pm" src="https://cloud.githubusercontent.com/assets/14326883/12071373/8c8bb83e-b0a9-11e5-8191-e574a1857c7c.png">

Similar to the Fwitter lab, this lab's "View on GitHub" link is not available:

<img width="1058" alt="screen shot 2016-01-01 at 5 00 34 pm" src="https://cloud.githubusercontent.com/assets/14326883/12071376/a8186584-b0a9-11e5-9962-866bdec90c8c.png">

However the "Raise an Issue" link brings me here to the learn-co-curriculum account. That must have been how I got the wrong version of the Fwitter lab. I won't make the same mistake again. I'll wait for an update to the student version.

Hope you had a nice NYE!

**Comment by AnnJohn** [comment]
Hi @onyoo thanks! We're looking into it right now and should have it fixed soon. Hope you had a great NYE as well!

**Comment by AnnJohn** [comment]
hi @onyoo this should be fixed now. thanks!
