### ISSUE TITLE
keep running into issue running rspec on this lab

### ISSUE THREAD

**Issue by drewvpham** [learn-co-curriculum/rails-activerecord-model-rails-lab#5]
learn
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:290: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/selector/simple_sequence.rb:91: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/selector/simple_sequence.rb:164: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/selector/simple_sequence.rb:207: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/selector/simple_sequence.rb:207: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/script/functions.rb:2422: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/script/functions.rb:2554: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/script/parser.rb:49: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/script/parser.rb:49: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/script/parser.rb:376: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/script/parser.rb:402: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/script/parser.rb:606: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/script/parser.rb:606: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/scss/parser.rb:512: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-3.4.21/lib/sass/scss/static_parser.rb:65: warning: literal in condition
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sass-rails-5.0.4/lib/sass/rails/helpers.rb:6: warning: method redefined; discarding old asset_data_url
/home/nitrous/code/labs/rails-activerecord-model-rails-lab-v-000/.bundle/gems/sprockets-3.5.2/lib/sprockets/sass_processor.rb:253: warning: previous definition of asset_data_url was he
re

**Comment by bhollan** [comment]
I'm hitting the exact same issue.

I'm running Ubuntu locally (not Nitrous).
