### ISSUE TITLE
No tests?

### ISSUE THREAD

**Issue by CodesAFK** [learn-co-curriculum/rails-activerecord-model-rails-lab#8]
When I forked and cloned the lab, the Student model rspec didn't have a test.  It had a "pending" but nothing over that.  I ended up writing the tests, which I didn't really mind, but I wish it would have been included in the instructions.  They currently seem to imply that the tests are built in.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for taking the time to contribute to our curriculum. 

The master (default) branch of this repository should include specs for  the [student model](https://github.com/learn-co-curriculum/rails-activerecord-model-rails-lab/blob/master/spec/models/student_spec.rb).

If you are still having trouble with the specs could you re-clone the repository, apply your solution and try to run the specs again. Please feel free to reopen the issue if the student specs are still missing.

Thanks! 💙
